apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-simple-api
  namespace: default
  labels:
    component: http-simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: http-simple-api
  template:
    metadata:
      labels:
        component: http-simple-api
    spec:
      containers:
        - name: http-simple-api
          image: juliocesarmidia/http-simple-api:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: http-port
            initialDelaySeconds: 10
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: http-port
            initialDelaySeconds: 10
            timeoutSeconds: 30
          env:
            - name: MESSAGE
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: API_PORT
              value: "9000"
          resources:
            limits:
              memory: "64Mi"
              cpu: "20m"
            requests:
              memory: "32Mi"
              cpu: "10m"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: http-simple-api
  namespace: default
  labels:
    component: http-simple-api
spec:
  type: ClusterIP
  selector:
    component: http-simple-api
  ports:
  - port: 80
    targetPort: http-port
    protocol: TCP

---

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: api
#   namespace: default
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # nginx.ingress.kubernetes.io/rewrite-target: "/api/v1/"
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

# spec:
#   rules:
#   - host: api.default.local
#     http:
#       paths:
#       - path: /api/v1/
#         # pathType: ImplementationSpecific
#         # pathType: Prefix
#         pathType: Exact
#         backend:
#           serviceName: api
#           servicePort: 80
#       - path: /api/v1/healthcheck
#         # pathType: ImplementationSpecific
#         # pathType: Prefix
#         pathType: Exact
#         backend:
#           serviceName: api
#           servicePort: 80
