apiVersion: v1
kind: Secret
data:
{{- with .Values.secrets }}
    {{- toYaml . | nindent 2 }}
{{- end }}
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.selectorLabels" . | nindent 6 }}