global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 1m

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    basic_auth:
      username: admin
      password: L4SlYsfPkja85jh32aV1
    follow_redirects: true
    static_configs:
    - targets:
      - localhost:9090

  - job_name: gomicroapi
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
    - targets:
      - go-micro-api:9000
