global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

    basic_auth:
      username: admin
      password: L4SlYsfPkja85jh32aV1

  - job_name: gomicroapi
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
    - targets:
      - go-micro-api:9000
