apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-simple-api
  namespace: default
  labels:
    app.kubernetes.io/name: http-simple-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # maximum of 1 replica to be created for each time
      maxUnavailable: 1 # maximum of 1 replica unavailable
  selector:
    matchLabels:
      app.kubernetes.io/name: http-simple-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-simple-api
    spec:
      containers:
        - name: http-simple-api
          image: juliocesarmidia/http-simple-api:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: /api/v1/health/live
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health/ready
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
          env:
          - name: MESSAGE
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            limits:
              memory: "32Mi"
              cpu: "20m"
            requests:
              memory: "16Mi"
              cpu: "10m"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: http-simple-api
  namespace: default
  labels:
    app.kubernetes.io/name: http-simple-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: http-simple-api
  ports:
  - port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-simple-api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - host: api.golang.local
    http:
      paths:
      - path: /api/v1/message
        pathType: Exact
        backend:
          serviceName: http-simple-api
          servicePort: 80
      - path: /api/v1/health/
        pathType: Prefix
        backend:
          serviceName: http-simple-api
          servicePort: 80
