{
 "title": "API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request count endpoint [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gomicroapi_http_request_duration_seconds_count{uri!=\"/metrics\"}[1m])",
     "legendFormat": "{{path}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Response time average [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(gomicroapi_http_request_duration_seconds_sum{path!=\"/metrics\"}[1m])) by (job)\r\n  /\r\nsum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\"}[1m])) by (job)",
     "legendFormat": "{{path}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Latency quartiles average [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(gomicroapi_http_request_duration_seconds_bucket{path!=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "99 %"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(gomicroapi_http_request_duration_seconds_bucket{path!=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "90 %"
    },
    {
     "expr": "histogram_quantile(0.75, sum(increase(gomicroapi_http_request_duration_seconds_bucket{path!=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "75 %"
    },
    {
     "expr": "histogram_quantile(0.50, sum(increase(gomicroapi_http_request_duration_seconds_bucket{path!=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "50 %"
    },
    {
     "expr": "histogram_quantile(0.25, sum(increase(gomicroapi_http_request_duration_seconds_bucket{path!=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "25 %"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\",status=\"500\"}[1m])) / sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\"}[1m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\",status=\"400\"}[1m])) / sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\"}[1m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\",status=\"405\"}[1m])) / sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\"}[1m]))",
     "legendFormat": "405"
    },
    {
     "expr": "sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\",status=\"404\"}[1m])) / sum(increase(gomicroapi_http_request_duration_seconds_count{path!=\"/metrics\"}[1m]))",
     "legendFormat": "404"
    }
   ]
  }
 ]
}