replicaCount: 1
image:
  repository: juliocesarmidia/go-micro-api
  pullPolicy: IfNotPresent
  tag: "v1.0.0"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
service:
  type: ClusterIP
  sourcePort: 9000
  targetPort: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: api.golang.local
      paths:
      - path: /api/v1/message
        pathType: Exact
      - path: /api/v1/configuration
        pathType: Exact
      - path: /api/v1/ping
        pathType: Exact
      - path: /api/v1/health/
        pathType: Prefix
      - path: /metrics
        pathType: Exact
  tls: []
  #  - secretName: go-micro-api-tls
  #    hosts:
  #      - api.golang.local
resources:
  limits:
    memory: "32Mi"
    cpu: "20m"
  requests:
    memory: "16Mi"
    cpu: "10m"
livenessUrl: "/api/v1/health/live"
readinessUrl: "/api/v1/health/ready"
configmaps:
  MESSAGE: "Hello World From Kubernetes"
secrets: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
